[package]
name = "infra-keyval"
version = "0.1.1"
edition = "2021"

[dependencies]
axum = { version = "0.8.7", features = ["http1", "tokio"], default-features = false }
keyv = { version = "0.2.1", features = ["postgres"] }
serde_json = "1.0.145"
tokio = "1.48.0"
